drinks = [
	{name: 'Kopi'},
	{name: 'Kopi C'},
	{name: 'Kopi O'},
	{name: 'Kopi Peng'},
	{name: 'Kopi O Siew Dai'},
	{name: 'Kopi O Kosong'},
	{name: 'Teh'},
	{name: 'Teh C'},
	{name: 'Teh O'},
	{name: 'Teh Peng'},
	{name: 'Teh O Siew Dai'},
	{name: 'Teh O Kosong'},
	{name: 'Coke'},
	{name: 'Coke Light'},
	{name: 'Coke Zero'},
	{name: 'Ice Lemon Tea'},
	{name: 'Barley'},
];
