drinks = [
	{name: 'ICE WHITE COFFEE', category: 'cold'},
	{name: 'ICE LIPTON TEA', category: 'cold'},
	{name: 'ICE LIPTON TEA WITH MILK', category: 'cold', category: 'cold'},
	{name: 'ICE LEMON TEA', category: 'cold'},
	{name: 'ICE MILO', category: 'cold'},
	{name: 'JUMBO MILO DINOSAUR', category: 'cold'},
	{name: 'BLENDED ICE LIME JUICE', category: 'cold'},
	{name: 'BLENDED ICE LIME JUICE W/ SOUR PLUM', category: 'cold'},
	{name: 'SJORA MANGO', category: 'cold'},
	{name: 'FRESH COCONUT JUICE', category: 'cold'},
	{name: 'ROSE SYRUP', category: 'cold'},
	{name: 'ROSE SYRUP W/ LIME', category: 'cold'},
	{name: 'ROSE BANDUNG', category: 'cold'},
	{name: 'ICE HONEY LEMON', category: 'cold'},
	{name: 'COKE FLOAT (VANILLA)', category: 'cold'},
	{name: 'COKE', category: 'cold'},
	{name: 'COKE ZERO', category: 'cold'},
	{name: 'SPRITE', category: 'cold'},
	{name: 'AQUARIUS ISOTONIC', category: 'cold'},
	{name: 'SOYA BEAN', category: 'cold'},
	{name: 'CHRYSANTHEMUM', category: 'cold'},
	{name: 'H&E GREEN TEA', category: 'cold'},
	{name: 'RIBENNA (PACKET)', category: 'cold'},
	{name: 'MINERAL WATER', category: 'cold'},
	{name: 'COLD ICE WATER', category: 'cold'},
	{name: 'FRUIT PUNCH', category: 'cold'},
	{name: 'NESCAFE BLACK COFFEE', category: 'hot'},
	{name: 'NESCAFE COFFEE (CONDENSED MILK)', category: 'hot'},
	{name: 'NESCAFE COFFEE (EVAPORATED MILK)', category: 'hot'},
	{name: 'NESCAFE WHITE COFFEE', category: 'hot'},
	{name: 'CAPPUCCINO', category: 'hot'},
	{name: 'MOCHA', category: 'hot'},
	{name: 'TEH TARIK', category: 'hot'},
	{name: 'LIPTON TEA', category: 'hot'},
	{name: 'LIPTON TEA (CONDENSED MILK)', category: 'hot'},
	{name: 'LIPTON TEA (EVAPORATED MILK)', category: 'hot'},
	{name: 'LIPTON TEA W/ LEMON', category: 'hot'},
	{name: 'MILO', category: 'hot'},
	{name: 'CHRYSANTHEMUM', category: 'hot'},
	{name: 'CHINESE TEA', category: 'hot'},
	{name: 'HONEY LEMON', category: 'hot'},
	{name: 'WARM WATER', category: 'hot'},
	{name: 'HOT WATER', category: 'hot'},
	{name: 'BLUE OCEAN', category: 'misc'},
	{name: 'PEACH COOLER', category: 'misc'},
	{name: 'VIRGIN MOJITO', category: 'misc'},
	{name: 'GREEN FOREST', category: 'misc'}
];